# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- '*'

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  rootFolderOrFile: '/d/Nitesh/Git/mydemo'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- script: 'echo "$(Build.DefinitionName), $(Build.BuildId), $(Build.BuildNumber)"'
  displayName: 'Write build info'

- script: 'echo "$(Build.BinariesDirectory), $(Build.ArtifactStagingDirectory), $(buildConfiguration)"'
  displayName: 'Write system variable'

- script: 'echo "$(buildConfiguration), $(rootFolderOrFile)"'
  displayName: 'Write user variable'

# Archive files
# Compress files into .7z, .tar.gz, or .zip
- task: ArchiveFiles@2
  displayName: "Archive files"
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)/publish_output' 
    includeRootFolder: true 
    #archiveType: 'zip' # Options: zip, 7z, tar, wim
    #tarCompression: 'gz' # Optional. Options: gz, bz2, xz, none
    #archiveFile: '$(Build.ArtifactStagingDirectory).zip'
    #archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip' 
    archiveFile: "$(System.DefaultWorkingDirectory)/build$(Build.BuildId).zip"
    replaceExistingArchive: true 
    verbose: true
    quiet: false

- script: 'echo "$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip"'
  displayName: 'Writing a message'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)/build$(Build.BuildId).zip'